#include "cmap_paths.h"

#include <string.h>

#include "logger/log.h"
#include "pdf_error/error.h"

// This function was auto-generated by `scripts/code-gen/gen_cmap_paths.py`.
PdfError* pdf_cmap_name_to_path(char* cmap_name, const char** cmap_path_out) {
    RELEASE_ASSERT(cmap_name);
    RELEASE_ASSERT(cmap_path_out);

    if (strcmp("Adobe-CNS1-0", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/Adobe-CNS1-0";
    } else if (strcmp("Adobe-CNS1-1", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/Adobe-CNS1-1";
    } else if (strcmp("Adobe-CNS1-2", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/Adobe-CNS1-2";
    } else if (strcmp("Adobe-CNS1-3", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/Adobe-CNS1-3";
    } else if (strcmp("Adobe-CNS1-4", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/Adobe-CNS1-4";
    } else if (strcmp("Adobe-CNS1-5", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/Adobe-CNS1-5";
    } else if (strcmp("Adobe-CNS1-6", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/Adobe-CNS1-6";
    } else if (strcmp("Adobe-CNS1-7", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/Adobe-CNS1-7";
    } else if (strcmp("B5-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/B5-H";
    } else if (strcmp("B5-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/B5-V";
    } else if (strcmp("B5pc-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/B5pc-H";
    } else if (strcmp("B5pc-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/B5pc-V";
    } else if (strcmp("CNS-EUC-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/CNS-EUC-H";
    } else if (strcmp("CNS-EUC-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/CNS-EUC-V";
    } else if (strcmp("CNS1-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/CNS1-H";
    } else if (strcmp("CNS1-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/CNS1-V";
    } else if (strcmp("CNS2-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/CNS2-H";
    } else if (strcmp("CNS2-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/CNS2-V";
    } else if (strcmp("ETHK-B5-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/ETHK-B5-H";
    } else if (strcmp("ETHK-B5-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/ETHK-B5-V";
    } else if (strcmp("ETen-B5-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/ETen-B5-H";
    } else if (strcmp("ETen-B5-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/ETen-B5-V";
    } else if (strcmp("ETenms-B5-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/ETenms-B5-H";
    } else if (strcmp("ETenms-B5-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/ETenms-B5-V";
    } else if (strcmp("HKdla-B5-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/HKdla-B5-H";
    } else if (strcmp("HKdla-B5-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/HKdla-B5-V";
    } else if (strcmp("HKdlb-B5-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/HKdlb-B5-H";
    } else if (strcmp("HKdlb-B5-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/HKdlb-B5-V";
    } else if (strcmp("HKgccs-B5-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/HKgccs-B5-H";
    } else if (strcmp("HKgccs-B5-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/HKgccs-B5-V";
    } else if (strcmp("HKm314-B5-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/HKm314-B5-H";
    } else if (strcmp("HKm314-B5-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/HKm314-B5-V";
    } else if (strcmp("HKm471-B5-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/HKm471-B5-H";
    } else if (strcmp("HKm471-B5-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/HKm471-B5-V";
    } else if (strcmp("HKscs-B5-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/HKscs-B5-H";
    } else if (strcmp("HKscs-B5-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-CNS1-7/CMap/HKscs-B5-V";
    } else if (strcmp("UniCNS-UCS2-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-CNS1-7/CMap/UniCNS-UCS2-H";
    } else if (strcmp("UniCNS-UCS2-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-CNS1-7/CMap/UniCNS-UCS2-V";
    } else if (strcmp("UniCNS-UTF16-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-CNS1-7/CMap/UniCNS-UTF16-H";
    } else if (strcmp("UniCNS-UTF16-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-CNS1-7/CMap/UniCNS-UTF16-V";
    } else if (strcmp("UniCNS-UTF32-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-CNS1-7/CMap/UniCNS-UTF32-H";
    } else if (strcmp("UniCNS-UTF32-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-CNS1-7/CMap/UniCNS-UTF32-V";
    } else if (strcmp("UniCNS-UTF8-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-CNS1-7/CMap/UniCNS-UTF8-H";
    } else if (strcmp("UniCNS-UTF8-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-CNS1-7/CMap/UniCNS-UTF8-V";
    } else if (strcmp("Adobe-GB1-0", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/Adobe-GB1-0";
    } else if (strcmp("Adobe-GB1-1", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/Adobe-GB1-1";
    } else if (strcmp("Adobe-GB1-2", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/Adobe-GB1-2";
    } else if (strcmp("Adobe-GB1-3", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/Adobe-GB1-3";
    } else if (strcmp("Adobe-GB1-4", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/Adobe-GB1-4";
    } else if (strcmp("Adobe-GB1-5", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/Adobe-GB1-5";
    } else if (strcmp("Adobe-GB1-6", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/Adobe-GB1-6";
    } else if (strcmp("GB-EUC-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GB-EUC-H";
    } else if (strcmp("GB-EUC-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GB-EUC-V";
    } else if (strcmp("GB-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GB-H";
    } else if (strcmp("GB-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GB-V";
    } else if (strcmp("GBK-EUC-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBK-EUC-H";
    } else if (strcmp("GBK-EUC-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBK-EUC-V";
    } else if (strcmp("GBK2K-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBK2K-H";
    } else if (strcmp("GBK2K-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBK2K-V";
    } else if (strcmp("GBKp-EUC-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBKp-EUC-H";
    } else if (strcmp("GBKp-EUC-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBKp-EUC-V";
    } else if (strcmp("GBT-EUC-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBT-EUC-H";
    } else if (strcmp("GBT-EUC-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBT-EUC-V";
    } else if (strcmp("GBT-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBT-H";
    } else if (strcmp("GBT-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBT-V";
    } else if (strcmp("GBTpc-EUC-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBTpc-EUC-H";
    } else if (strcmp("GBTpc-EUC-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBTpc-EUC-V";
    } else if (strcmp("GBpc-EUC-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBpc-EUC-H";
    } else if (strcmp("GBpc-EUC-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/GBpc-EUC-V";
    } else if (strcmp("UniGB-UCS2-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/UniGB-UCS2-H";
    } else if (strcmp("UniGB-UCS2-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/UniGB-UCS2-V";
    } else if (strcmp("UniGB-UTF16-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/UniGB-UTF16-H";
    } else if (strcmp("UniGB-UTF16-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/UniGB-UTF16-V";
    } else if (strcmp("UniGB-UTF32-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/UniGB-UTF32-H";
    } else if (strcmp("UniGB-UTF32-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/UniGB-UTF32-V";
    } else if (strcmp("UniGB-UTF8-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/UniGB-UTF8-H";
    } else if (strcmp("UniGB-UTF8-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-GB1-6/CMap/UniGB-UTF8-V";
    } else if (strcmp("Identity-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Identity-0/CMap/Identity-H";
    } else if (strcmp("Identity-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Identity-0/CMap/Identity-V";
    } else if (strcmp("78-EUC-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/78-EUC-H";
    } else if (strcmp("78-EUC-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/78-EUC-V";
    } else if (strcmp("78-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/78-H";
    } else if (strcmp("78-RKSJ-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/78-RKSJ-H";
    } else if (strcmp("78-RKSJ-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/78-RKSJ-V";
    } else if (strcmp("78-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/78-V";
    } else if (strcmp("78ms-RKSJ-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/78ms-RKSJ-H";
    } else if (strcmp("78ms-RKSJ-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/78ms-RKSJ-V";
    } else if (strcmp("83pv-RKSJ-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/83pv-RKSJ-H";
    } else if (strcmp("90ms-RKSJ-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/90ms-RKSJ-H";
    } else if (strcmp("90ms-RKSJ-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/90ms-RKSJ-V";
    } else if (strcmp("90msp-RKSJ-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/90msp-RKSJ-H";
    } else if (strcmp("90msp-RKSJ-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/90msp-RKSJ-V";
    } else if (strcmp("90pv-RKSJ-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/90pv-RKSJ-H";
    } else if (strcmp("90pv-RKSJ-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/90pv-RKSJ-V";
    } else if (strcmp("Add-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/Add-H";
    } else if (strcmp("Add-RKSJ-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/Add-RKSJ-H";
    } else if (strcmp("Add-RKSJ-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/Add-RKSJ-V";
    } else if (strcmp("Add-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/Add-V";
    } else if (strcmp("Adobe-Japan1-0", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/Adobe-Japan1-0";
    } else if (strcmp("Adobe-Japan1-1", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/Adobe-Japan1-1";
    } else if (strcmp("Adobe-Japan1-2", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/Adobe-Japan1-2";
    } else if (strcmp("Adobe-Japan1-3", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/Adobe-Japan1-3";
    } else if (strcmp("Adobe-Japan1-4", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/Adobe-Japan1-4";
    } else if (strcmp("Adobe-Japan1-5", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/Adobe-Japan1-5";
    } else if (strcmp("Adobe-Japan1-6", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/Adobe-Japan1-6";
    } else if (strcmp("Adobe-Japan1-7", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/Adobe-Japan1-7";
    } else if (strcmp("EUC-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/EUC-H";
    } else if (strcmp("EUC-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/EUC-V";
    } else if (strcmp("Ext-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/Ext-H";
    } else if (strcmp("Ext-RKSJ-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/Ext-RKSJ-H";
    } else if (strcmp("Ext-RKSJ-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/Ext-RKSJ-V";
    } else if (strcmp("Ext-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/Ext-V";
    } else if (strcmp("H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/H";
    } else if (strcmp("Hankaku", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/Hankaku";
    } else if (strcmp("Hiragana", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/Hiragana";
    } else if (strcmp("Katakana", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/Katakana";
    } else if (strcmp("NWP-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/NWP-H";
    } else if (strcmp("NWP-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/NWP-V";
    } else if (strcmp("RKSJ-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/RKSJ-H";
    } else if (strcmp("RKSJ-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/RKSJ-V";
    } else if (strcmp("Roman", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/Roman";
    } else if (strcmp("UniJIS-UCS2-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS-UCS2-H";
    } else if (strcmp("UniJIS-UCS2-HW-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS-UCS2-HW-H";
    } else if (strcmp("UniJIS-UCS2-HW-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS-UCS2-HW-V";
    } else if (strcmp("UniJIS-UCS2-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS-UCS2-V";
    } else if (strcmp("UniJIS-UTF16-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS-UTF16-H";
    } else if (strcmp("UniJIS-UTF16-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS-UTF16-V";
    } else if (strcmp("UniJIS-UTF32-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS-UTF32-H";
    } else if (strcmp("UniJIS-UTF32-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS-UTF32-V";
    } else if (strcmp("UniJIS-UTF8-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS-UTF8-H";
    } else if (strcmp("UniJIS-UTF8-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS-UTF8-V";
    } else if (strcmp("UniJIS2004-UTF16-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS2004-UTF16-H";
    } else if (strcmp("UniJIS2004-UTF16-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS2004-UTF16-V";
    } else if (strcmp("UniJIS2004-UTF32-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS2004-UTF32-H";
    } else if (strcmp("UniJIS2004-UTF32-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS2004-UTF32-V";
    } else if (strcmp("UniJIS2004-UTF8-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS2004-UTF8-H";
    } else if (strcmp("UniJIS2004-UTF8-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJIS2004-UTF8-V";
    } else if (strcmp("UniJISPro-UCS2-HW-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJISPro-UCS2-HW-V";
    } else if (strcmp("UniJISPro-UCS2-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJISPro-UCS2-V";
    } else if (strcmp("UniJISPro-UTF8-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJISPro-UTF8-V";
    } else if (strcmp("UniJISX0213-UTF32-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJISX0213-UTF32-H";
    } else if (strcmp("UniJISX0213-UTF32-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJISX0213-UTF32-V";
    } else if (strcmp("UniJISX02132004-UTF32-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJISX02132004-UTF32-H";
    } else if (strcmp("UniJISX02132004-UTF32-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Japan1-7/CMap/UniJISX02132004-UTF32-V";
    } else if (strcmp("V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/V";
    } else if (strcmp("WP-Symbol", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Japan1-7/CMap/WP-Symbol";
    } else if (strcmp("Adobe-KR-0", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-KR-9/CMap/Adobe-KR-0";
    } else if (strcmp("Adobe-KR-1", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-KR-9/CMap/Adobe-KR-1";
    } else if (strcmp("Adobe-KR-2", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-KR-9/CMap/Adobe-KR-2";
    } else if (strcmp("Adobe-KR-3", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-KR-9/CMap/Adobe-KR-3";
    } else if (strcmp("Adobe-KR-4", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-KR-9/CMap/Adobe-KR-4";
    } else if (strcmp("Adobe-KR-5", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-KR-9/CMap/Adobe-KR-5";
    } else if (strcmp("Adobe-KR-6", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-KR-9/CMap/Adobe-KR-6";
    } else if (strcmp("Adobe-KR-7", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-KR-9/CMap/Adobe-KR-7";
    } else if (strcmp("Adobe-KR-8", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-KR-9/CMap/Adobe-KR-8";
    } else if (strcmp("Adobe-KR-9", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-KR-9/CMap/Adobe-KR-9";
    } else if (strcmp("UniAKR-UTF16-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-KR-9/CMap/UniAKR-UTF16-H";
    } else if (strcmp("UniAKR-UTF32-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-KR-9/CMap/UniAKR-UTF32-H";
    } else if (strcmp("UniAKR-UTF8-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-KR-9/CMap/UniAKR-UTF8-H";
    } else if (strcmp("Adobe-Korea1-0", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/Adobe-Korea1-0";
    } else if (strcmp("Adobe-Korea1-1", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/Adobe-Korea1-1";
    } else if (strcmp("Adobe-Korea1-2", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/Adobe-Korea1-2";
    } else if (strcmp("KSC-EUC-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Korea1-2/CMap/KSC-EUC-H";
    } else if (strcmp("KSC-EUC-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Korea1-2/CMap/KSC-EUC-V";
    } else if (strcmp("KSC-H", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Korea1-2/CMap/KSC-H";
    } else if (strcmp("KSC-Johab-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/KSC-Johab-H";
    } else if (strcmp("KSC-Johab-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/KSC-Johab-V";
    } else if (strcmp("KSC-V", cmap_name) == 0) {
        *cmap_path_out = "assets/cmap-resources/Adobe-Korea1-2/CMap/KSC-V";
    } else if (strcmp("KSCms-UHC-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/KSCms-UHC-H";
    } else if (strcmp("KSCms-UHC-HW-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/KSCms-UHC-HW-H";
    } else if (strcmp("KSCms-UHC-HW-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/KSCms-UHC-HW-V";
    } else if (strcmp("KSCms-UHC-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/KSCms-UHC-V";
    } else if (strcmp("KSCpc-EUC-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/KSCpc-EUC-H";
    } else if (strcmp("KSCpc-EUC-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/KSCpc-EUC-V";
    } else if (strcmp("UniKS-UCS2-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/UniKS-UCS2-H";
    } else if (strcmp("UniKS-UCS2-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/UniKS-UCS2-V";
    } else if (strcmp("UniKS-UTF16-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/UniKS-UTF16-H";
    } else if (strcmp("UniKS-UTF16-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/UniKS-UTF16-V";
    } else if (strcmp("UniKS-UTF32-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/UniKS-UTF32-H";
    } else if (strcmp("UniKS-UTF32-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/UniKS-UTF32-V";
    } else if (strcmp("UniKS-UTF8-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/UniKS-UTF8-H";
    } else if (strcmp("UniKS-UTF8-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Korea1-2/CMap/UniKS-UTF8-V";
    } else if (strcmp("Adobe-Manga1-0", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Manga1-0/CMap/Adobe-Manga1-0";
    } else if (strcmp("UniManga-UTF16-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Manga1-0/CMap/UniManga-UTF16-H";
    } else if (strcmp("UniManga-UTF16-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Manga1-0/CMap/UniManga-UTF16-V";
    } else if (strcmp("UniManga-UTF32-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Manga1-0/CMap/UniManga-UTF32-H";
    } else if (strcmp("UniManga-UTF32-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Manga1-0/CMap/UniManga-UTF32-V";
    } else if (strcmp("UniManga-UTF8-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Manga1-0/CMap/UniManga-UTF8-H";
    } else if (strcmp("UniManga-UTF8-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/Adobe-Manga1-0/CMap/UniManga-UTF8-V";
    } else if (strcmp("Adobe-Japan2-0", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/deprecated/Adobe-Japan2-0/CMap/Adobe-Japan2-0";
    } else if (strcmp("Hojo-EUC-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/deprecated/Adobe-Japan2-0/CMap/Hojo-EUC-H";
    } else if (strcmp("Hojo-EUC-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/deprecated/Adobe-Japan2-0/CMap/Hojo-EUC-V";
    } else if (strcmp("Hojo-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/deprecated/Adobe-Japan2-0/CMap/Hojo-H";
    } else if (strcmp("Hojo-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/deprecated/Adobe-Japan2-0/CMap/Hojo-V";
    } else if (strcmp("UniHojo-UCS2-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/deprecated/Adobe-Japan2-0/CMap/UniHojo-UCS2-H";
    } else if (strcmp("UniHojo-UCS2-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/deprecated/Adobe-Japan2-0/CMap/UniHojo-UCS2-V";
    } else if (strcmp("UniHojo-UTF16-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/deprecated/Adobe-Japan2-0/CMap/UniHojo-UTF16-H";
    } else if (strcmp("UniHojo-UTF16-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/deprecated/Adobe-Japan2-0/CMap/UniHojo-UTF16-V";
    } else if (strcmp("UniHojo-UTF32-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/deprecated/Adobe-Japan2-0/CMap/UniHojo-UTF32-H";
    } else if (strcmp("UniHojo-UTF32-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/deprecated/Adobe-Japan2-0/CMap/UniHojo-UTF32-V";
    } else if (strcmp("UniHojo-UTF8-H", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/deprecated/Adobe-Japan2-0/CMap/UniHojo-UTF8-H";
    } else if (strcmp("UniHojo-UTF8-V", cmap_name) == 0) {
        *cmap_path_out =
            "assets/cmap-resources/deprecated/Adobe-Japan2-0/CMap/UniHojo-UTF8-V";
    } else {
        return PDF_ERROR(
            PDF_ERR_UNKNOWN_CMAP,
            "CMap with name `%s` is not a known asset",
            cmap_name
        );
    }

    return NULL;
}
