name: Build & Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - name: clang-17
            cc: clang-17
            cxx: clang++-17
            packages: clang-17 clang-tidy-17
          - name: gcc-14
            cc: gcc-14
            cxx: g++-14
            packages: gcc-14 g++-14
      fail-fast: false
    name: Build with ${{ matrix.compiler.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Install ${{ matrix.compiler.name }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.compiler.packages }}

      - name: Configure build
        run: |
          CC=${{ matrix.compiler.cc }} CXX=${{ matrix.compiler.cxx }} cmake -B build-${{ matrix.compiler.name }} \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build
        run: |
          cmake --build build-${{ matrix.compiler.name }} -- -j$(nproc)

      - name: Run tests
        run: |
          build-${{ matrix.compiler.name }}/libs/test/pdf-test-main
